@baseUrl=http://localhost:9000

GET {{baseUrl}}/hello
###
###
get {{baseUrl}}/blockchain/check
###
get {{baseUrl}}/blockchain/totalsupply

###
POST {{baseUrl}}/blockchain/setmessage
Content-Type: application/json

{
    "setmessage" : "Welcome2EthereumClient-2"
}
###

GET {{baseUrl}}/blockchain/getmessage

###
POST {{baseUrl}}/blockchain/transfertokens
Content-Type: application/json

{
    "accountnumber" : "1",
    "totaltokens" : 1
}
###

###
# router.get('/gettokens/:account', blockchain_controller.ACCOUNT_TOKEN_BALANCE)
get {{baseUrl}}/blockchain/gettokens/2

###

###
POST {{baseUrl}}/blockchain/transferfrom
Content-Type: application/json

{
    "accountnumberfrom" : "1",
    "accountnumberto" : "2",
    "totaltokens" : 1
}
###

POST {{baseUrl}}/smartcontract/deploy
Content-Type: application/json

{
    "tokenname" : "1",
    "totaltokens" : "2",
    "tokendescription" : "ERC20 TOKEN SCB"
}